/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fi.helsinki.btls;

import com.google.gson.Gson;
import fi.helsinki.btls.domain.LocationModel;
import fi.helsinki.btls.io.IMqttProvider;
import fi.helsinki.btls.io.UbiMqttProvider;
import fi.helsinki.btls.services.ILocationService;
import fi.helsinki.btls.services.IMqttService;
import fi.helsinki.btls.services.LocationService2D;
import fi.helsinki.btls.services.MqttService;
import fi.helsinki.btls.utils.PropertiesHandler;

import java.util.List;
import java.util.Map;

public class App {
    public static void main(String[] args) throws Exception {
        IMqttProvider provider = new UbiMqttProvider();
        IMqttService mqttService = new MqttService(provider, new Gson());
        ILocationService service = new LocationService2D();
        Map<String, String> allProperties = new PropertiesHandler("config/rasps.properties").getAllProperties();



        while(true) {
            try {
                Thread.sleep(1000);
                List<LocationModel> locations = service.calculateAllLocations(mqttService.getBeacons());

                for (LocationModel location : locations) {
                    mqttService.publish(location);
                }
            } catch (Exception ex) {
                System.out.println(ex.toString());
            }
        }
    }
}
